### ISSUE TITLE
Deadlock Integration

### ISSUE THREAD

**Issue by Nuozrok** [Nuozrok/lpap#21]
![image](https://github.com/user-attachments/assets/22c71391-ccb7-4030-9ef7-e25661705f5c)

**Comment by whig123** [comment]
requirements

provide easier to follow patch notes 
provide  # of times you matched against a haze (weekly, monthly, YTD)
 - compare to global pick rate of haze?
 - info about haze players met from prior matches (rank? account? region?)

**Comment by whig123** [comment]
to find the # of times you matched against a haze,

you need to:

find your steam ID (do we want manual mapping, or user input? maybe you enter it once and that's it?)
find your match history (use https://analytics.deadlock-api.com/v2/players/{steam ID}/match-history
extract X Match ID's from the match-history 
for each Match ID:
call https://data.deadlock-api.com/v1/matches/{Match ID}/metadata
within the players list, scrape the hero_id of each player and find how many occurrences are of hero_id =13 (haze)

congrats you have # of times played against a haze in last X games
